import mongoose from "mongoose";

const defaultCreator = new mongoose.Types.ObjectId("65f2a3d1234567890abcdef1");

const artifacts = [
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Ancient Sword",
    description: "A sword from ancient times",
    content: "This is an ancient sword.",
    riddle: "What is sharp and ancient?",
    unlockAnswer: "Ancient Sword",
    area: "Overworld",
    isExclusive: false,
    image: "/assets/ancient_sword.png",
    creator: defaultCreator,
    location: { x: 3, y: 2 },
    type: "artifact",
    messageText: "",
    exp: 10,
    visible: true,
    status: "world",
    unlockCondition: "Answer the riddle correctly"
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Mystic Orb",
    description: "A mysterious orb",
    content: "This is a mystic orb.",
    riddle: "What is round and mystic?",
    unlockAnswer: "Mystic Orb",
    area: "Overworld",
    isExclusive: false,
    image: "/assets/mystic_orb.png",
    creator: defaultCreator,
    location: { x: 7, y: 5 },
    type: "artifact",
    messageText: "",
    exp: 15,
    visible: true,
    status: "world",
    unlockCondition: "Answer the riddle correctly"
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Golden Idol",
    description: "A golden idol",
    content: "This is a golden idol.",
    riddle: "What is golden and worshipped?",
    unlockAnswer: "Golden Idol",
    area: "Desert",
    isExclusive: false,
    image: "/assets/golden_idol.png",
    creator: defaultCreator,
    location: { x: 4, y: 6 },
    type: "artifact",
    messageText: "",
    exp: 20,
    visible: true,
    status: "world",
    unlockCondition: "Answer the riddle correctly"
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Dungeon Key",
    description: "A key to the dungeon",
    content: "This is a dungeon key.",
    riddle: "What unlocks the dungeon?",
    unlockAnswer: "Dungeon Key",
    area: "Dungeon",
    isExclusive: false,
    image: "/assets/dungeon_key.png",
    creator: defaultCreator,
    location: { x: 5, y: 5 },
    type: "artifact",
    messageText: "",
    exp: 25,
    visible: true,
    status: "world",
    unlockCondition: "Answer the riddle correctly"
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Enchanted Mirror",
    description: "A silver mirror that whispers secrets.",
    content: "Gazing into the mirror reveals glimpses of forgotten memories.",
    riddle: "I speak without a mouth and hear without ears. What am I?",
    unlockAnswer: "echo",
    area: "Overworld",
    isExclusive: true,
    image: "/assets/enchanted_mirror.png",
    creator: defaultCreator,
    type: "artifact",
    messageText: "The mirror speaks: 'Beware the shadows in the glade.'",
    location: { x: 8, y: 3 },
    exp: 30,
    visible: true,
    status: "world",
    unlockCondition: "Answer the riddle correctly"
  }
];

export default artifacts;